<a href="https://colab.research.google.com/github/nbartecka/Probability_Statistics/blob/main/Nikola_Bartecka_lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Stats Notebook Lab #3

### Loops

In [1]:
for i in range(100): #ask python to print the first 100 numbers 
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [ ]:
for i in range(5,8): #ask python to print every number from 5-8 
    print(i)

5
6
7


In [ ]:
for i in range(3):
    print( "Test Number: " , i ) #ask python to print the first 3 numbers with certain text in front of it

Test Number:  0
Test Number:  1
Test Number:  2


### Functions

In [ ]:
def square(x): #square (a number, x) is defined by the code for squaring a number 
    return x**2

In [3]:
square(5) #demonstrates function 


NameError: ignored

In [ ]:
square(square(2)) #squares 2 (= 4) then squares 4

16

In [ ]:
square(square(square(2))) #squares 2 ( = 4) then squares ( = 16 )then squares 16


256

In [ ]:
square(123456)

15241383936

In [ ]:
square(square(5)) #squares 5 ( = 25 ) then squares 25

625

In [ ]:
def add_two(x): #function to add 2 to a number, x
    return x+2

In [ ]:
add_two(5) #demonstrates function 

7

In [ ]:
square(add_two(5)) #uses both functions to add 2 to 5 and square that number ((5+2)^2)

49

### Logical Branching

In [ ]:
choice = "apple" #one equal is an assignment operator

In [ ]:
if choice == "apple": # 2 equal signs means a test of an operation or function 

    print("You choose apples.")

else: #tells python that if it does not show one phrase it shows the other 
    
    print("You did not choose apples.")

You choose apples.


In [ ]:
choice = "orange"

In [ ]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You did not choose apples.


In [ ]:
choice = "apple"

In [ ]:
if choice == "apple":

    print("You choose apples.")
    print("Thank you, shop again!")
    print(2**123)

elif choice == "orange": #elif means "else if" an alternative to the first choice 

    print("You choose oranges.")
    print("Thank you, shop again!")

else:
    
    print("You did not choose apples or oranges.")
    print("Thank you, shop again!")

You choose apples.
Thank you, shop again!
10633823966279326983230456482242756608


### User Input

In [ ]:
choice = input("Please enter your choice (i.e. apple): ") #input allows the user to type in a text box

Please enter your choice (i.e. apple): oranges


In [ ]:
choice #displays what the user typed

'oranges'

In [ ]:
if choice == "apple":

    print("You choose apples.")

elif choice == "oranges":

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.") #evaluates what the user typed and decided if it was under "if" or "elif", or neither 

You choose oranges.


#### Coins

In [4]:
import numpy as np

In [5]:
np.random.random() #generate random number between 0 and 1

0.36720775314902987

In [6]:
np.random.random() > 0.5 #if the number generated is greater than 0.5 the output is true

False

In [7]:
def flip_coin(): #heads vs tails function
    if np.random.random() > 0.5:
        print("Heads") #if value is greater than 0.5 show heads
    else:
        print("Tails") #if the value is less than 0.5 show tails

In [8]:
flip_coin() #ask python to generate number between 0 and 1 and display assigned output depending on value

Tails


### Graphics Output

In [9]:
from IPython.core.display import display, HTML

In [10]:
display(HTML('<h1>Hello, world!</h1>'))

In [11]:
def coin():
  return np.random.randint(2) #function coin() is defined by a command asking to choose randomly between the first 2 numbers 

In [12]:
coin() #running np.random.randint(2) under its function name

1

In [13]:
display(HTML('<img src="https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg">')) #shows image using HTML

In [14]:
heads = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg'
tails = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-back.jpg' #defines heads and tails variables

In [15]:
def show_img(img):
  display(HTML('<img src=' + img + '>')) #defines function to display either heads or tail image

In [16]:
show_img(heads) #show heads image

In [17]:
show_img(tails) #show tails image

In [18]:
def flip_coin(): #define coin flip function

    if coin(): #tells python when to show heads
        show_img(heads)
    else: #tells python that if it does not show heads show tails
        show_img(tails)

In [19]:
flip_coin() #an actual coin flip

In [20]:
for i in range(5): #flip coin 5 times
    flip_coin()

In [ ]:
#@title Coin Flip

if coin():

  show_img(heads)

else:

  show_img(tails)

### Cards

In [21]:
def shuffle(x):
    for i in range(len(x)-1,0,-1):
        j = np.random.randint(0,i+1)
        x[i],x[j] = x[j],x[i]
        # print(j,x)
    return x

In [22]:
a = np.arange(52)  #shows the first 52 numbers

In [23]:
shuffle(a) #shuffles the first 52 numbers 

array([ 1, 34, 24, 40, 35, 18, 16, 23, 14, 26, 47, 46, 32, 11,  6, 49, 29,
       22, 10, 36,  4, 28, 27,  9, 21,  0, 37, 45,  2, 48,  5, 42, 13, 39,
       15, 33, 17, 38, 44, 51, 50, 43,  3, 20, 30, 31, 12, 19, 25,  8,  7,
       41])

In [24]:
np.random.permutation(52) #function to directly get the first 52 numbers and shuffle them 

array([19,  4,  8, 17, 34, 10,  0, 44,  2, 27, 12, 29, 42, 40, 30, 14, 16,
       50,  6, 23, 22, 36, 11, 20, 15, 31, 33, 45, 25, 51, 32, 41, 24, 28,
       39, 49,  5,  9, 38, 46,  3, 18, 48, 35,  7,  1, 37, 47, 43, 13, 26,
       21])

### Speed Test

In [26]:
%%timeit
shuffle(a) #measures how long the cell took to execute the comand 

207 µs ± 39.3 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [27]:
%%timeit
np.random.permutation(52)

3.56 µs ± 126 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [28]:
import numpy as np

In [29]:
np.random.permutation(52)

array([18, 14,  3, 33, 36, 45, 15, 48, 22,  8,  9, 12, 20, 26, 27, 28, 10,
       50, 29, 43, 37, 46, 47, 40,  7,  2,  0, 19, 32,  6,  4, 34, 23, 16,
        1, 11, 39, 41, 21, 24, 13, 35,  5, 38, 31, 49, 30, 17, 42, 51, 25,
       44])

In [30]:
cards = np.random.permutation(52) #variable defined by the function

In [31]:
import numpy as np

In [32]:
cards = np.random.permutation(52) #variable defined by the function

In [33]:
cards #displays function

array([ 6, 23, 35,  4, 31,  5, 17, 44,  0, 43,  9, 48, 19, 34, 40, 10, 37,
       18, 20, 38, 36, 11, 41, 13, 25, 30, 16, 15, 50,  1, 24, 47, 22, 46,
       27, 42, 28, 51, 33,  3,  7, 26, 32,  2, 12, 49, 39, 29,  8, 45, 21,
       14])

In [34]:
cards[0] #shows the first number in array

6

In [35]:
cards[1] #shows the second number in array

23

In [36]:
cards[2] #shows the third number in array

35

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [ ]:
np.arange(52).reshape(4,13) #reshape the list of numbers into 4 rows by 13 columns

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [ ]:
np.arange(52).reshape(4,13)%13 #modulo operator

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [ ]:
np.arange(52).reshape(4,13)//13 # 2 forward slashes means floor division

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [ ]:
suits = ['Clubs','Spades','Hearts','Diamonds'] # 4 different card suits 
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

In [ ]:
def card_name(card_number):
    
    suit = card_number//13 #perform floor division for card suits 
    name = card_number%13 #use modulo operator for card names 

    return names[name] + " of " + suits[suit] #output is "__ of __"

In [ ]:
card_name(0) #demonstrates function for first card

'Ace of Clubs'

In [ ]:
card_name(51) #demonstrates for 52nd card

'King of Diamonds'

In [ ]:
cards = np.random.permutation(52) #new variable using random shuffling of 52 cards

In [ ]:
top_of_deck         = card_name(cards[0]) #cells first card in deck by card_name function 
second_card_in_deck = card_name(cards[1]) #second card
last_card_in_deck   = card_name(cards[-1]) #-1 is another way of saying 51 last card in deck

In [ ]:
top_of_deck, second_card_in_deck, last_card_in_deck #output of command

('Three of Hearts', 'Nine of Diamonds', 'Ten of Hearts')

In [ ]:
for i in range(5):
    print(card_name(cards[i])) #python gives the first 5 cards from the shuffled deck

Four of Spades
Six of Diamonds
Ace of Diamonds
Eight of Clubs
Three of Diamonds


In [ ]:
for i in range(15):
    print(card_name(cards[i])) #python gives the first 15 cards from the shuffled deck

Seven of Hearts
Ace of Clubs
King of Diamonds
Four of Hearts
Two of Hearts
Three of Spades
Ace of Diamonds
Seven of Diamonds
Four of Diamonds
King of Clubs
Five of Hearts
Three of Hearts
Six of Diamonds
Nine of Hearts
Eight of Hearts


https://www.improvemagic.com/all-playing-cards-names-with-pictures/

In [ ]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/" #url for image of playing  cards
card_url_tail = ".png"

In [ ]:
suit = ['k','p','s','l'] #4 different suits 
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k'] #13 different cards

In [ ]:
i = np.random.randint(4) #give a random number up to 4 
j = np.random.randint(13) #give a random number up to 13

In [ ]:
i,j #give both numbers as a coordinate 

(0, 11)

In [ ]:
suit[i] #give the value i that python generated

'k'

In [ ]:
card[j] #give the value j that python generated

'q'

In [ ]:
from IPython.core.display import display, HTML #import HTML in python

In [ ]:
def show_img(img): #defines function to display card image based on randomly generated card 
  display(HTML('<img src=' + img + '>'))

In [ ]:
img = card_url_head + suit[i] + card[j] + card_url_tail #variable for card image

In [ ]:
show_img(img) #displays ace of diamonds the random card generated by i and j 

In [ ]:
def card_image(card_number):
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j] #output is the coordinate of the card in a 13x4 table

In [ ]:
card_image(3) #displays coordinates of 4th card

'k4'

In [ ]:
img = card_url_head + card_image(3) + card_url_tail #variable for card image

In [ ]:
show_img(img) #displays card defined by coordinates "k4"

In [ ]:
for i in range(52):
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img) #displays all 52 cards using img variable 